### ISSUE TITLE
Improve CI test failure detection

### ISSUE THREAD

**Issue by terrykong** [NVIDIA/JAX-Toolbox#60]
At the moment CI tests can succeed as long as an error has not occurred. Some tests should fail if the perf or accuracy drops below some threshold.

We should create a re-usable workflow that can parse raw values or TB logs and update badges based on whether they've met some acceptance criteria

**Comment by yhtang** [comment]
Good point. I had that in mind for a while but lacked the bandwidth to make it happen. However, I don't think we should let the test 'fail' the hard way if, for example, perf falls below a certain threshold. Because in that case, the test successfully runs and performs its duty to measure perf. Instead, we could render some badges in a warning color, send notification emails, or even automatically file issues based on the measurement.

**Comment by mjsML** [comment]
+1 re filing issues automatically.

**Comment by terrykong** [comment]
> Because in that case, the test successfully runs and performs its duty to measure perf.

@yhtang That's true; conflating the workflow job success signal with the "perf" signal is not helpful for those debugging. I agree that it would be better to have a badge reflect the "perf" or "accuracy" failure (and the auto filing issue feat). I changed the title to reflect that.

Proposal for what I was thinking. I guess we can separate the logic into two reusable workflows:

1. A workflow just to create a badge based on an expression
```yaml
acceptable-loss:
    uses: ./.github/workflows/_acceptance_badge.yaml
    with:
      badge_label: 't5x convergence'  # t5x perf
      value_or_dir: ${{ jobs.run-job.outputs.loss_value }}
      condition: "[[ $val -gt 0.5 ]] && [[ $val -lt 1.0 ]]
      issue_assignee: <name>@nvidia.com
```

2. A reusable workflow that can be added as a final step for jobs with TB logs
```yaml
tensorboard-extract:
    uses: ./.github/workflows/_tensorboard_extract.yaml
    with:
      dir: ${{ jobs.run-job.outputs.tensorboard_dir }}
      metric_name: train/timing/examples_per_second_per_core
      reduction: none # mean || max || min
```

(1) can be done easily, and for (2), we can probably make use of [EventAccumulator](https://github.com/tensorflow/tensorboard/blob/master/tensorboard/backend/event_processing/event_accumulator.py)

Thoughts?
