### ISSUE TITLE
Consolidate workflows that could be "matrix"-ified but depend on multiple parents 

### ISSUE THREAD

**Issue by terrykong** [NVIDIA/JAX-Toolbox#72]
This issue is to keep track of an improvement to this PR https://github.com/NVIDIA/JAX-Toolbox/pull/65 that's not possible with current GH Action machinery.

## Issue:
The build CI will soon build a t5x and paxml rosetta distribution once #65 is merged. We can combine the building and testing into a single workflow, but the issue is that the trigger would look like this:
```yaml
name: Nightly Rosetta build and test

on:
  workflow_run:
    workflows: [Nightly T5x build,Nightly Pax build]
    types: [completed]
    branches: [main]

jobs:
  build-and-test:
  strategy:
     matrix:
        BASE_LIBRARY: [t5x, pax]
```

But this workflow triggers when ANY of the `on.workflow_run.workflows` finishes; which would lead to a race condition b/c the downstream rosetta build may use an older t5x or paxml image.

## Related
* There's a discussion about this very issue here https://github.com/orgs/community/discussions/16059
* In general, this race condition of images b/c we use the "latest" tag in downstream tests is tracked here #63 

## Concerns
Even if conjunctive logic is implemented for `on.workflow_run.workflows` today, it would mean wasting some time not starting the first build.
